version: "3.9"
services:
  database:
    image: postgis/postgis
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
      timeout: 3s
      retries: 3

  jupyter:
    image: noaa-hydro-data
    environment:
      - AWS_PROFILE=noaa
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/:/opt/src/
      - ./data/:/opt/data/
      - $HOME/.aws:/home/jovyan/.aws:ro
    ports:
      - 8888:8888
    working_dir: /opt/src
    platform: linux/amd64
    depends_on:
      database:
        condition: service_healthy
    command:
      - "notebook"
      - "--ip=0.0.0.0"
      - "--no-browser"
      - "--allow-root"

volumes:
  pgdata: