version: '2.3'
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform
      args:
        - KUBECTL_VERSION=${KUBECTL_VERSION:-v1.23.6}
        - HELM_VERSION=${HELM_VERSION:-v3.8.2}
        - USER=${USER}
        - UID
        - GID
    image: terraform-docker
    volumes:
      - ../:/usr/local/src
      - $HOME/.aws:/home/$USER/.aws:ro
      - $HOME/.kube:/home/$USER/.kube
      - /var/run/docker.sock:/var/run/docker.sock:rw
    environment:
      - AWS_PROFILE
      - AWS_DEFAULT_REGION
      - USER
      - VERSION_TAG
      - NOAA_DEBUG
      - EDITOR=vi
      - NOAA_SETTINGS_S3_PATH=${NOAA_SETTINGS_S3_PATH:-noaa-settings/us-east-1/staging}
    working_dir: /usr/local/src/deployment
    entrypoint: bash
