#!/bin/bash

set -e

if [[ -n "${AMERICAN_WATER_TANK_MAGIC_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Run a psql shell inside the database container.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker-compose exec database psql -U postgres
    fi
fi
