#!/bin/bash

set -e

if [[ -n "${NOAA_HYDRO_DATA_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Provision a development environment.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        pip3 install -U nbdev
        nbdev_install_hooks
        ./scripts/update
    fi
fi
