#!/bin/bash

set -e

if [[ -n "${NOAA_HYDR_DATA_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        # Ensure container images are current
        docker-compose build
    fi
fi
