#!/bin/bash

set -ex

if [[ -n "${NOAA_SETTINGS_S3_PATH}" ]]; then
   TFVARS_S3_PATH=s3://$NOAA_SETTINGS_S3_PATH/terraform.tfvars
else
   echo "Please define NOAA_SETTINGS_S3_PATH before proceeding"
   exit 1
fi

TO_EDIT_TMP_FILE=$(mktemp)
TO_COMPARE_TMP_FILE=$(mktemp)

aws --quiet s3 cp --sse AES256 "${TFVARS_S3_PATH}" "${TO_EDIT_TMP_FILE}"

cp -f "${TO_EDIT_TMP_FILE}" "${TO_COMPARE_TMP_FILE}"

if [[ -n "${EDITOR}" ]]; then
    "${EDITOR}" "${TO_EDIT_TMP_FILE}"
else
    echo "Please specify an EDITOR!"
    rm ${TO_EDIT_TMP_FILE} ${TO_COMPARE_TMP_FILE}
    exit 1
fi

if ! cmp -s "${TO_EDIT_TMP_FILE}" "${TO_COMPARE_TMP_FILE}"; then
  echo
  (diff -a -u "${TO_COMPARE_TMP_FILE}" "${TO_EDIT_TMP_FILE}") || true
  echo
  read -p "Does that look reasonable? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
      aws --quiet s3 cp --sse AES256 "${TO_EDIT_TMP_FILE}" "${TFVARS_S3_PATH}"
  fi
else
  echo "No changes to upload"
fi

rm ${TO_EDIT_TMP_FILE} ${TO_COMPARE_TMP_FILE}
